services:
  backend_laravel:
    image: irfnysin/backend-bissakerja:${APP_VERSION}
    container_name: backend_laravel
    # volumes:
    #   - ./:/var/www/html
    volumes:
      - /root/jatim-bissa/backend:/public
    working_dir: /var/www/html
    command: php artisan serve --host=0.0.0.0 --port=8000
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    network_mode: host
    restart: unless-stopped
