version: "3.8"

services:
 laravel:
    image: irfnysin/laravel:latest
    container_name: laravel_app
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: db_jatim_bissa
      DB_USERNAME: db_jatim_bissa
      DB_PASSWORD: xWsd38YFsXxsbTtS
      APP_ENV: production
      APP_DEBUG: false
    volumes:
      - laravel_storage:/var/www/html/storage
    networks:
      - laravel_net

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_jatim_bissa
      MYSQL_USER: db_jatim_bissa
      MYSQL_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - laravel_net

 
volumes:
  mysql_data:
  laravel_storage:

networks:
  laravel_net:
    driver: bridge
