services:
  backend_laravel:
    image: irfnysin/backend-bissakerja:${APP_VERSION}
    container_name: backend_laravel
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      # persist app uploads/logs; code comes from the image
      - /root/jatim-bissa/backend/storage:/var/www/html/storage
      - /root/jatim-bissa/backend/public:/var/www/html/public
    working_dir: /var/www/html
    # keep php-fpm as the main process, and prep Laravel at start
    entrypoint: ["/bin/sh", "-lc"]
    command: >
      'php artisan key:generate --force || true
       php artisan storage:link || true
       php artisan migrate --force || true
       php artisan config:cache
       php artisan route:cache
       php-fpm'
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
