version: "3.8"

services:
  laravel:
    image: irfnysin/laravel:latest
    container_name: laravel_app
    restart: unless-stopped
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_DATABASE=db_jatim_bissa
      - DB_USERNAME=db_jatim_bissa
      - DB_PASSWORD=xWsd38YFsXxsbTtS
      - APP_ENV=production
      - APP_DEBUG=false
    network_mode: host
    volumes:
      - laravel_storage:/var/www/html/storage
      - laravel_storage:/val/www/html/public

volumes:
  laravel_storage:
