services:
  backend_laravel:
    image: irfnysin/backend-bissakerja:1.0.0
    container_name: backend_laravel
    # volumes:
    #   - ./:/var/www/html
    volumes:
      - /root/jatim-bissa/backend/public:/var/www/html/public
      - /root/jatim-bissa/backend/storage:/var/www/html/storage
    working_dir: /var/www/html
    command: php artisan serve --host=127.0.0.1 --port=8000
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    network_mode: host
    restart: unless-stopped
