name: backend-bissakerja deployment
on:
  push:
    branches: [main]

env:
  IMAGE_NAME: irfnysin/backend-bissakerja

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get package version
        run: echo "APP_VERSION=$(grep '\"version\"' composer.json | head -1 | awk -F '\"' '{print $4}')" >> $GITHUB_ENV

      - name: Build image
        run: docker build -t $IMAGE_NAME:${{ env.APP_VERSION }} .

      - name: Login registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.IMAGE_REGISTRY_USERNAME }}
          password: ${{ secrets.IMAGE_REGISTRY_TOKEN }}

      - name: Push image
        run: docker push $IMAGE_NAME:${{ env.APP_VERSION }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Get package version (same method)
        run: echo "APP_VERSION=$(grep '\"version\"' composer.json | head -1 | awk -F '\"' '{print $4}')" >> $GITHUB_ENV

      - name: Ensure compose dir on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p ~/jatim-bissa/backend

      - name: Copy compose file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "docker-compose.yml"
          target: "~/jatim-bissa/backend"

      - name: Deploy
        env:
          APP_VERSION: ${{ env.APP_VERSION }}
          DB_CONNECTION: mysql
          DB_HOST: localhost
          DB_PORT: "3306"
          DB_DATABASE: db_jatim_bissa
          DB_USERNAME: db_jatim_bissa
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          envs: APP_VERSION,DB_CONNECTION,DB_HOST,DB_PORT,DB_DATABASE,DB_USERNAME,DB_PASSWORD
          script: |
            cd ~/jatim-bissa/backend
            # Make sure the compose file uses the parametric tag
            sed -i 's|image: irfnysin/backend-bissakerja:.*|image: irfnysin/backend-bissakerja:${APP_VERSION}|' docker-compose.yml
            export APP_VERSION DB_CONNECTION DB_HOST DB_PORT DB_DATABASE DB_USERNAME DB_PASSWORD
            docker compose pull
            docker compose up -d
            docker image prune -f
