name: Deploy Laravel to Docker Hub & VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.IMAGE_REGISTRY_USERNAME }}
          password: ${{ secrets.IMAGE_REGISTRY_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t irfnysin/laravel:latest .
          docker push irfnysin/laravel:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/scp-action@master
        with:
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "docker-compose.yml"
          target: "~/laravel-app"

      - name: Run docker-compose on VPS
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ~/laravel-app
            docker compose pull
            docker compose down
            docker compose up -d
            docker image prune -f
            echo "✅ Deployment completed!"
