name: Deploy Laravel to Docker Hub & VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build -t irfnysin/laravel:latest .

      - name: Push Docker image
        run: docker push irfnysin/laravel:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker pull irfnysin/laravel:latest
            docker stop laravel_app || true
            docker rm laravel_app || true
            docker run -d --name laravel_app -p 8000:8000 irfnysin/laravel:latest
