name: backend-bissakerja deployment
on:
  push:
    branches: [main]

jobs:
  build:
    name: build image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Get package version
        run: echo "APP_VERSION=$(node -p "require('./composer.json').version")" >> $GITHUB_ENV

      - name: build image
        run: docker build -t irfnysin/backend-bissakerja:${{ env.APP_VERSION }} .

      - name: login registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.IMAGE_REGISTRY_USERNAME }}
          password: ${{ secrets.IMAGE_REGISTRY_TOKEN }}

      - name: push image
        run: docker push irfnysin/backend-bissakerja:${{ env.APP_VERSION }}

  deploy:
    name: deploy image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Get package version
        run: echo "APP_VERSION=$(node -p "require('./composer.json').version")" >> $GITHUB_ENV

      - name: Upsert compose folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p ~/deploy-bissakerja/backend

      - name: Run docker compose
        env:
          APP_VERSION: ${{ env.APP_VERSION }}
          DB_CONNECTION: mysql
          DB_HOST: localhost
          DB_PORT: 3306
          DB_DATABASE: db_jatim_bissa
          DB_USERNAME: db_jatim_bissa
          DB_PASSWORD: xWsd38YFsXxsbTtS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          envs: APP_VERSION,DB_CONNECTION,DB_HOST,DB_PORT,DB_DATABASE,DB_USERNAME,DB_PASSWORD
          script: |
            cd deploy-bissakerja/backend
            APP_VERSION="$APP_VERSION" \
            DB_CONNECTION="$DB_CONNECTION" \
            DB_HOST="$DB_HOST" \
            DB_PORT="$DB_PORT" \
            DB_DATABASE="$DB_DATABASE" \
            DB_USERNAME="$DB_USERNAME" \
            DB_PASSWORD="$DB_PASSWORD" \
            docker compose up --build -d --no-deps
